#pragma once
//#include <QGuiApplication>
//#include <QQmlApplicationEngine>
//#include <QNetworkAccessManager>
//#include <QObject>
//#include <QProcess>
//#include <QAbstractListModel>
//#include <QHash>
//#include <QByteArray>
//#include <QNetworkAccessManager>
//#include <QNetworkReply>
//#include <QQmlContext>
